obstacle_range: 3.0
raytrace_range: 3.5
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.30
inflation_radius: 0.30
cost_scaling_factor: 5.0


observation_sources: laser_scan_sensor 
laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

