global_costmap:
  global_frame: /map2
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true
  #width: 20.0
  #height: 20.0
  #origin_x: -10.0
  #origin_y: -10.0
  inflation_radius: 0.60

